---
- hosts: all
  become: true
  tasks:
    - name: Debug - Información de sistema
      task:
        commands:
        - echo "Versión de sistema operativo:"
        - uname -a
        - echo "Comandos disponibles en el entorno:"
        - compgen -c | sort
