--- 
- name: Deploy Docker image Prueba integración con https. Utilizo fine-grained token Acceso desde gitlab
  hosts: webserver
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: hello-world
        source: pull
        tag: latest

    - name: Start Docker container
      docker_container:
        name: hello_world_container
        image: hello-world:latest
        state: started



        